name: Buf Lint & Breaking Check

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  buf-check:
    name: Run Buf Checks
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Buf CLI
        uses: bufbuild/buf-setup-action@v1
        with:
          version: 1.51.0

      - name: Lint .proto files
        run: buf lint

      - name: Check for breaking changes
        run: buf breaking --against '.git#branch=origin/main'
